version: "3.10.11"
services:
  shell:
    container_name: "aiden_shell"
    build: .
    volumes:
      - .:/ai
    env_file:
      - ./docker/shell.env
    command: [/bin/bash, -c, sleep infinity, alias aiden_start="python3 main.py text"]
